# Generated by Django 3.2.7 on 2021-09-25 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.TextField(max_length=200, verbose_name='Широта')),
                ('longitude', models.TextField(max_length=200, verbose_name='Долгота')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('imgpath', models.CharField(max_length=200, verbose_name='Фото категории походу')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Phone'), ('2', 'Facebook'), ('3', 'Email')], max_length=1, verbose_name='Тип')),
                ('value', models.TextField(max_length=200, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='', verbose_name='Фото логотипа')),
                ('branches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses312.branch', verbose_name='походу филиал')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses312.category', verbose_name='Категория')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses312.contact', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
