# Generated by Django 3.2.7 on 2021-09-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses312', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imgpath',
            field=models.ImageField(upload_to='media', verbose_name='Фото категории походу'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('1 phone', 'Phone'), ('2 facebook', 'Facebook'), ('3 email', 'Email')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(upload_to='media', verbose_name='Фото логотипа'),
        ),
    ]
