# Generated by Django 3.2.7 on 2021-09-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses312', '0002_auto_20210925_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('1-phone', 'Phone'), ('2-facebook', 'Facebook'), ('3-email', 'Email')], max_length=20, verbose_name='Тип'),
        ),
    ]
