# Generated by Django 3.2.7 on 2021-10-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses312', '0003_alter_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
