# Generated by Django 3.2.7 on 2021-10-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses312', '0004_alter_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='branches',
        ),
        migrations.AddField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(to='courses312.Branch', verbose_name='походу филиал'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='contacts',
        ),
        migrations.AddField(
            model_name='course',
            name='contacts',
            field=models.ManyToManyField(to='courses312.Contact', verbose_name='Контакты'),
        ),
    ]
