# Generated by Django 3.2.7 on 2021-10-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses312', '0006_alter_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(max_length=200, verbose_name='Значение'),
        ),
    ]
