# Generated by Django 3.2.7 on 2021-10-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses312', '0007_alter_contact_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('phone', 'Phone'), ('2-facebook', 'Facebook'), ('3-email', 'Email')], max_length=30, verbose_name='Тип'),
        ),
    ]
